In [1]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np
y_true=["cat","ant","cat","cat","ant","bird"]
y_pred=["ant","ant","cat","cat","ant","cat"]
cm=confusion_matrix(y_true,y_pred,labels=["ant","cat","bird"])   #Confusion Matrix
print(metrics.classification_report(y_true,y_pred))
print(cm)

D:\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

        ant       0.67      1.00      0.80         2
       bird       0.00      0.00      0.00         1
        cat       0.67      0.67      0.67         3

avg / total       0.56      0.67      0.60         6

[[2 0 0]
 [1 2 0]
 [0 1 0]]


In [2]:
y_true=[3,2,2,4]
y_pred=[3,1,2,8]
print(metrics.mean_absolute_error(y_true,y_pred))
print(metrics.mean_squared_error(y_true,y_pred))

1.25
4.25
