In [1]:
import pandas as pd
import numpy as np

In [2]:
def actFunc(haha,choose):
    if choose==1:
        return (1/(1+np.exp(haha)))
    elif choose==2:
        return np.max(0,haha)
    elif choose==3:
        return np.tanh(haha)
    elif choose==4:
        temp=np.exp(haha)
        return temp/np.sum(temp,axis=1,keepdims=True)

In [3]:
def forwardPass(Data):
    a0=Data;
    z1=np.dot(a0,w1)+b1
    a1=actFunc(z1,3)
    z2=np.dot(a1,w2)+b2
    a2=actFunc(z2,4)
    return a0,z1,a1,z2,a2
    

In [4]:
dfa= pd.read_csv('C:/Users/PRIYAL SOBTIPRIYAL.1/Desktop/label1.csv',header=None)
print(dfa)
arr=np.array(dfa);
print(arr)
data= pd.read_csv('C:/Users/PRIYAL SOBTIPRIYAL.1/Desktop/data1.csv',header=None)
print(data)
arr1=np.array(data)
print(arr1)
ans=np.eye(5)[arr]
print(ans)
ans1=np.reshape(ans,(20000,5))
print(ans1)

       0
0      3
1      2
2      2
3      3
4      3
5      3
6      0
7      3
8      3
9      0
10     1
11     0
12     3
13     1
14     3
15     3
16     3
17     3
18     2
19     2
20     2
21     0
22     4
23     3
24     0
25     3
26     4
27     0
28     2
29     3
...   ..
19970  3
19971  2
19972  3
19973  0
19974  0
19975  3
19976  2
19977  2
19978  4
19979  4
19980  1
19981  0
19982  3
19983  0
19984  1
19985  0
19986  2
19987  0
19988  2
19989  3
19990  1
19991  1
19992  3
19993  1
19994  1
19995  3
19996  1
19997  2
19998  2
19999  0

[20000 rows x 1 columns]
[[3]
 [2]
 [2]
 ...
 [2]
 [2]
 [0]]
             0         1         2         3         4         5         6   \
0     -0.446891 -0.013397  0.232645  2.156649  1.652923 -0.210531 -0.662227   
1      0.243747 -1.144175 -0.622214 -0.661979 -0.373315  0.520313 -1.307954   
2     -1.417799 -0.088833 -0.647181 -1.141497 -1.321100  0.686798 -1.045569   
3      0.656784  0.381201 -1.039011  1.285315  0.808324  1.42851

In [5]:
from sklearn.model_selection import train_test_split
trainData,testData=train_test_split(arr1,train_size=0.8,test_size=0.2,shuffle=False)
print(trainData)
print(testData)

[[-0.44689111 -0.01339702  0.23264493 ... -0.94587809  1.84092189
  -0.27902404]
 [ 0.24374694 -1.14417545 -0.62221358 ...  0.90293107 -1.41872787
  -0.29013935]
 [-1.41779879 -0.0888327  -0.647181   ...  1.20946469 -1.52638614
   0.33777109]
 ...
 [ 0.22011405 -0.96713629 -1.04358102 ... -1.15681152 -1.84186749
  -2.92789517]
 [ 0.25507184  2.87268234  0.79673767 ... -0.58069011  1.27553944
   2.73832272]
 [-0.14117311 -1.55003665 -0.74873535 ... -0.65376916 -0.52611073
   0.19844164]]
[[-0.38027962 -1.50842897  0.14112986 ... -0.53700322  1.27739799
   0.22462058]
 [ 0.5249627  -0.23104331  0.49815571 ...  0.15860512  1.77466194
  -1.1714302 ]
 [ 0.40653738  1.48479942 -0.30536028 ...  0.97056971  0.40420801
  -0.83502482]
 ...
 [-0.80040466  1.47799654  0.0900574  ...  0.37866958  0.11096771
  -0.17636265]
 [-1.21734449 -0.78540102 -0.41378073 ...  0.24927734 -0.94149613
   1.66166061]
 [ 1.60100517 -0.89039824 -1.42504908 ... -0.02377265  1.2208092
   1.48933029]]


In [6]:
trainLabel,TestLabel=train_test_split(ans1,train_size=0.8,test_size=0.2,shuffle=False)
print(trainLabel)
print(TestLabel)

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [7]:
validationLabel,TestLabel=train_test_split(TestLabel,train_size=0.5,test_size=0.5,shuffle=False)
validationData,testData=train_test_split(testData,train_size=0.5,test_size=0.5,shuffle=False)
print(validationLabel)
print(TestLabel)
print(validationData.shape)
print(testData.shape)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
(2000, 20)
(2000, 20)


In [8]:
h=input()#no of neurons in hidden layer
h=int(h)

10


In [9]:
b1=np.zeros(h)
b2=np.zeros(5)
print(b1)
print(b2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [10]:
std1=(1/np.sqrt(20))#standard deviation of initialiing first weights
std2=(1/np.sqrt(h))#standard deviation of initialiing second weights
w1=np.random.normal(0,std1,(20,h))#gaussian random assignment of weight
w2=np.random.normal(0,std2,(h,5))#gaussian random assignment of weights 
#print("std1\n",std1,"std2\n",std2)
print("w1\n",w1)
print("w2\n",w2)
print(w1.shape) #w1 has the dimensions 20 X 10
print(w2.shape) #w2 has the dimensions 10X5

w1
 [[ 3.22661722e-01 -2.66211184e-01  2.86157713e-01 -1.52182629e-01
   3.90528447e-03 -1.41133022e-01 -3.33823413e-02 -3.05610219e-02
  -1.47763263e-01  1.39389979e-03]
 [ 2.85823598e-02  4.75772940e-01 -3.19537242e-01 -1.66459642e-02
   3.40741913e-01 -9.83906783e-03 -7.39032980e-02 -1.32605768e-01
  -1.82157385e-01  3.79128351e-01]
 [ 3.13626689e-01  2.03345114e-01 -3.74466658e-01 -1.03376311e-01
   1.67848848e-01 -9.25577750e-02 -4.02366087e-01  2.85730591e-02
   4.40705923e-04  1.40552739e-01]
 [ 4.67384003e-01 -4.57668591e-01  1.14252729e-01 -2.01053457e-02
  -2.17379881e-01 -9.40999949e-02 -4.25564761e-02 -2.83482970e-01
   4.45897533e-01  2.15766768e-01]
 [ 2.71549676e-01  1.15518801e-01  3.81664899e-01  2.92078801e-01
  -1.75419096e-01 -2.81758196e-01  5.32172223e-01  6.37462680e-02
  -1.42310095e-01 -1.46812227e-01]
 [-2.33399653e-01  3.00719010e-01  1.93085354e-01  1.49365941e-01
  -1.40663542e-01 -2.37969058e-02  3.14756002e-01 -5.17078799e-02
   1.30462799e-01  4.09574837

In [11]:
print(trainData.shape)

(16000, 20)


In [12]:
batch=input();
batch=int(batch)

100


In [13]:
epochs=input();

160


In [14]:
alpha=input();
alpha=float(alpha)

0.001


In [15]:
def costFunc(y,t):
    return -(t*np.log(y)+(1-t)*np.log(1-y))

In [16]:
def Accuracy(y,TrainLabel):
    maxintraindata=np.argmax(y,axis=1)
    maxinlabel=np.argmax(TrainLabel,axis=1)
    count=0
    for l in range(16000):
        if (maxintraindata[l]==maxinlabel[l]):
            count=count+1
    return (count/16000)*100
    

In [17]:
for j in range(int(epochs)):
    for i in range(int(16000/batch)):
        a0,z1,a1,z2,a2=forwardPass(trainData[i*batch:(i+1)*batch,:])
        y=a2
        LabelBatch=trainLabel[i*batch:(i+1)*batch,:]
        del2=y-LabelBatch
        del1=np.dot(del2,w2.T)*(1-pow(actFunc(z1,3),2))
        dcdw2=np.dot(a1.T,del2)
        dcdw1=np.dot(a0.T,del1)
        dcdb2=np.sum(del2,axis=0)
        dcdb1=np.sum(del1,axis=0)
        w1=w1-alpha*dcdw1
        w2=w2-alpha*dcdw2
        b1=b1-alpha*dcdb1
        b2=b2-alpha*dcdb2
    a0,z1,a1,z2,a2=forwardPass(trainData)
    ytrue=a2
    cost=np.sum(costFunc(ytrue,trainLabel))/16000
    print("cost")
    print(cost)
    accuracy=Accuracy(ytrue,trainLabel)
    print("Accuracy")
    print(accuracy)
    
      
        

cost
1.2172092161664654
Accuracy
76.66875
cost
1.039865899745394
Accuracy
79.96875
cost
0.9375953209761297
Accuracy
82.0
cost
0.8572846630294374
Accuracy
83.78125
cost
0.7980802478165239
Accuracy
85.2375
cost
0.7574909080836729
Accuracy
85.84375
cost
0.7275076813827744
Accuracy
86.4
cost
0.7018982559810747
Accuracy
86.8375
cost
0.6781232032604013
Accuracy
87.18125
cost
0.6571357123730742
Accuracy
87.65625
cost
0.6395072805840307
Accuracy
88.03750000000001
cost
0.6247460862690419
Accuracy
88.49375
cost
0.6122320578757627
Accuracy
88.81875000000001
cost
0.6015042167773749
Accuracy
89.1
cost
0.5922235262869173
Accuracy
89.35625
cost
0.5841247502038711
Accuracy
89.53750000000001
cost
0.576995857231022
Accuracy
89.66875
cost
0.5706685124143177
Accuracy
89.8375
cost
0.5650114146370402
Accuracy
89.9625
cost
0.5599247173125474
Accuracy
90.09375
cost
0.5553349765731569
Accuracy
90.29374999999999
cost
0.551189599447689
Accuracy
90.375
cost
0.5474497244365781
Accuracy
90.4625
cost
0.5440824691676

In [18]:
def Accuracy1(y,data):
    maxintraindata=np.argmax(y,axis=1)
    maxinlabel=np.argmax(data,axis=1)
    count=0
    for l in range(2000):
        if (maxintraindata[l]==maxinlabel[l]):
            count=count+1
    return (count/2000)*100

In [19]:
b0,m1,b1,m2,b2=forwardPass(validationData)
yt=b2
cost1=np.sum(costFunc(yt,validationLabel))/2000
print("cost1")
print(cost1)
accuracy1=Accuracy1(yt,validationLabel)
print("Accuracy")
print(accuracy1)
    

cost1
0.5078841463586402
Accuracy
90.60000000000001
